name: NTroll
version: "1.0"
author: NCraft
main: craft.ncraft.ntroll.NTroll
api-version: '1.15'
commands:
   ntroll:
    description: Main command
    permission: ntroll.command
   spawnmobbehind:
    description: Spawn a mob behind a player
    permission: ntroll.spawnmobbehind
   spawnarrow:
    description: Spawn an arrow to a player
    permission: ntroll.spawnarrow
   spawnshulkerbullet:
    description: Spawn an shulker bullet to a player
    permission: ntroll.spawnshulkerbullet
permissions:
  ntroll.command:
    description: Allows main command
    default: op
  ntroll.command.admin:
    description: Allows troll on/off/status
    default: op
  ntroll.spawnmobbehind:
    description: Allows spawning a mob behind a player
    default: op
  ntroll.spawnarrow:
    description: Allows spawning an arrow to a player
    default: op
  ntroll.spawnshulkerbullet:
    description: Allows spawning a shulker bullet to a player
    default: op